# Generated by Django 3.2.15 on 2024-05-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('in_process', 'Собирается'), ('in_delivery', 'В пути'), ('received', 'Получен')], db_index=True, default='accepted', max_length=20),
        ),
    ]
