# Generated by Django 3.2.15 on 2024-05-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20240527_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('in_process', 'Собирается'), ('in_delivery', 'В пути'), ('received', 'Получен')], db_index=True, default='accepted', max_length=20, verbose_name='статус'),
        ),
    ]
