# Generated by Django 3.2.15 on 2024-05-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20240528_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('electronic', 'Электронно'), ('cash', 'Наличными')], db_index=True, default='electronic', max_length=20, verbose_name='метод оплаты'),
        ),
    ]
