# Generated by Django 3.2.15 on 2024-05-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Электронно', 'Электронно'), ('Наличностью', 'Наличными')], db_index=True, default='Электронно', max_length=20, verbose_name='метод оплаты'),
        ),
    ]
